In [1]:
weight = 0.1 
def neural_network(input, weight):
    prediction = input * weight
    return prediction

number_of_toes = [8.5, 9.5, 10, 9]
input = number_of_toes[0]
pred = neural_network(input, weight)
print(pred)

0.8500000000000001


In [14]:
def w_sum(a, b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += (a[i] * b[i])
    return output

weights = [0.1, 0.2, 0] 
    
def neural_network(input, weights):
    pred = w_sum(input, weights)
    return pred
    
toes =  [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8,0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0], wlrec[0], nfans[0]]
pred = neural_network(input, weights)

print(pred)

0.9800000000000001


In [15]:
import numpy as np
weights = np.array([0.1, 0.2, 0])
def neural_network(input, weights):
    pred = input.dot(weights)
    return pred

toes =  np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65,0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

input = np.array([toes[0], wlrec[0], nfans[0]])
pred = neural_network(input, weights)

print(pred)

0.9800000000000001


In [16]:
            #toes %win #fans
weights = [ [0.1, 0.1,-0.3],  #hurt?
            [0.1, 0.2, 0.0],  #win?
            [0.0, 1.3, 0.1] ] #sad?

def w_sum(a, b):
    assert(len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += (a[i] * b[i])
    return output

def vect_mat_mul(vect, matrix):
    assert(len(vect) == len(matrix))
    output = [0, 0, 0]
    for i in range(len(vect)):
        output[i] = w_sum(vect, matrix[i])
    return output

def neural_network(input, weights):
    pred = vect_mat_mul(input, weights)
    return pred

toes =  [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65,0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0], wlrec[0], nfans[0]]
pred = neural_network(input, weights)

print(pred)

[0.555, 0.9800000000000001, 0.9650000000000001]


In [6]:
            #toes %win #fans
ih_wgt = [ [0.1, 0.2,-0.1],  #hid[0]
           [-0.1,0.1, 0.9],  #hid[1]
           [0.1, 0.4, 0.1] ] #hid[2]

           #hid[0] hid[1] hid[2]
hp_wgt = [ [0.3, 1.1,-0.3],  #hurt?
           [0.1, 0.2, 0.0],  #win?
           [0.0, 1.3, 0.1] ] #sad?

weights = [ih_wgt, hp_wgt]

def neural_network(input, weights):
    hid = vect_mat_mul(input, weights[0])
    pred = vect_mat_mul(hid, weights[1])
    return pred

toes =  [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65,0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0], wlrec[0], nfans[0]]
pred = neural_network(input, weights)

print(pred)

[0.21350000000000002, 0.14500000000000002, 0.5065]


In [17]:
import numpy as np

                      #toes %win #fans
ih_wgt = np.array( [ [0.1, 0.2,-0.1],      #hid[0]
                     [-0.1,0.1, 0.9],      #hid[1]
                     [0.1, 0.4, 0.1] ] ).T #hid[2]

                     #hid[0] hid[1] hid[2]
hp_wgt = np.array( [ [0.3, 1.1,-0.3],      #hurt?
                     [0.1, 0.2, 0.0],      #win?
                     [0.0, 1.3, 0.1] ] ).T #sad?

weights = [ih_wgt, hp_wgt]

def neural_network(input, weights):

    hid = input.dot(weights[0])
    pred = hid.dot(weights[1])
    return pred


toes =  np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65,0.8, 0.8, 0.9])
nfans = np.array([1.2, 1.3, 0.5, 1.0])

input = np.array([toes[0], wlrec[0], nfans[0]])

pred = neural_network(input, weights)
print(pred)

[0.2135 0.145  0.5065]


In [11]:
import numpy as np

a = np.array([0, 1, 2, 3])
b = np.array([4, 5, 6, 7])
c = np.array( [ [0, 1, 2, 3],
                [4, 5, 6, 7] ] )

d = np.zeros((2, 4))
e = np.random.rand(2, 5)

print(a)
print(b)
print(c)
print(d)
print(e)

print(a * 0.1)   
print(c * 0.2)   
print(a * b)   
print(a * b * 0.2)   
print(a * c)
print(a * e) #Error

[0 1 2 3]
[4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0.18883288 0.65380146 0.20365323 0.11770299 0.5232486 ]
 [0.42564655 0.78389612 0.18087819 0.6092577  0.10747367]]
[0.  0.1 0.2 0.3]
[[0.  0.2 0.4 0.6]
 [0.8 1.  1.2 1.4]]
[ 0  5 12 21]
[0.  1.  2.4 4.2]
[[ 0  1  4  9]
 [ 0  5 12 21]]


ValueError: operands could not be broadcast together with shapes (4,) (2,5) 

In [12]:
a = np.zeros((1, 4))
b = np.zeros((4, 3))

c = a.dot(b)
print(c.shape)

(1, 3)


In [13]:
a = np.zeros((2, 4))
b = np.zeros((4, 3))
c = a.dot(b)
print(c.shape) #(2, 3)

e = np.zeros((2, 1))
f = np.zeros((1, 3))
g = e.dot(f)
print(g.shape) #(2, 3)

h = np.zeros((5, 4)).T #(4, 5)
i = np.zeros((5, 6))
j = h.dot(i)
print(j.shape) #(4, 6)

h = np.zeros((5, 4))
i = np.zeros((5, 6))
j = h.dot(i)
print(j.shape) #Error

(2, 3)
(2, 3)
(4, 6)


ValueError: shapes (5,4) and (5,6) not aligned: 4 (dim 1) != 5 (dim 0)